server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://app-yandex-parser-back-service/api/;
        proxy_set_header Host app-yandex-parser-back-service;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /sanctum/ {
        proxy_pass http://app-yandex-parser-back-service/sanctum/;
        proxy_set_header Host app-yandex-parser-back-service;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}